name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      # Prepare dist directory (ensure it's always created early using bash for consistency)
      - name: Prepare dist directory
        shell: bash  # <--- Add this line
        run: mkdir -p dist

      # For macOS: compress and copy archive
      - name: Compress macOS binary
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          mkdir -p dist
          tar -czf dist/ubl-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release ubl

      # For Windows and Linux: copy binary directly
      - name: Prepare binary (non-macOS)
        if: matrix.os != 'macos-latest'
        shell: bash # <--- Add this line for the non-macOS step as well
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/ubl${{ matrix.ext }} dist/ubl-${{ matrix.target }}${{ matrix.ext }}

      - name: Upload release binaries
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}